
trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'
jobs:
- job: windows
  displayName: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      python2_32:
        python_version: 2
        python_exe_name: python.exe
      python2_64:
        python_version: 2
        python_exe_name: python64.exe
      python2_64pe:
        python_version: 3
        python_exe_name: python64_pe.exe
      python3_32:
        python_version: 3
        python_exe_name: python.exe
      python3_64:
        python_version: 3
        python_exe_name: python64.exe
      python3_64pe:
        python_version: 3
        python_exe_name: python64_pe.exe
  steps:
  - script: git config --global core.autoCRLF false
    displayName: "Disable git autoCRLF"
  - checkout: self
    displayName: "Checkout"
    fetchDepth: 50
  - script: pip install requests
    displayName: Install requests
  - script: python test/download_python.py $(python_exe_name) $(python_version)
    displayName: Download python
  - script: cmd /c test\test.cmd $(python_exe_name) $(python_version)
    displayName: Test
- job: github_release
  displayName: GitHub Release
  pool:
    vmImage: 'vs2017-win2016'
  dependsOn: windows
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  steps:
  - script: git config --global core.autoCRLF false
    displayName: "Disable git autoCRLF"
  - checkout: self
    displayName: "Checkout"
    fetchDepth: 50
  - script: python -c "import shutil; shutil.make_archive('pausable_unittest', 'zip', '.', 'pausable_unittest')"
    displayName: Create archive
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: 'github_connection'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'auto'
      tag: '$(Build.SourceBranchName)'
      assets: 'pausable_unittest.zip'
      assetUploadMode: 'replace'
      title: 'SampleTitle'
      releaseNotesSource: 'input'
      releaseNotes: ''
      isDraft: true
      isPreRelease: true
      addChangeLog: false
